## adjustments in data
## change names, symbols, etc

# function to adjust ranks
adjust_rank <- function (data) {
  # correct ranks
  data$TaxonomicRank[which(data$TaxonomicRank == "Phyllum")] <- "Phylum"
  data$TaxonomicRank[which(data$TaxonomicRank == "phyllum")] <- "Phylum"
  data$TaxonomicRank[which(data$TaxonomicRank == "phylum")] <- "Phylum"
  data$TaxonomicRank[which(data$TaxonomicRank == "subphylum")] <- "Subphylum"
  data$TaxonomicRank[which(data$TaxonomicRank == "Division")] <- "Phylum" # https://en.wikipedia.org/wiki/Division_(biology)#:~:text=Division%20is%20a%20taxonomic%20rank,a%20rank%20equivalent%20to%20phylum.
  data$TaxonomicRank[which(data$TaxonomicRank == "domain")] <- "Domain"
  data$TaxonomicRank[which(data$TaxonomicRank == "class")] <- "Class"
  data$TaxonomicRank[which(data$TaxonomicRank == "clade")] <- "Clade"
  data$TaxonomicRank[which(data$TaxonomicRank == "subclass")] <- "Subclass"
  data$TaxonomicRank[which(data$TaxonomicRank == "order")] <- "Order"
  data$TaxonomicRank[which(data$TaxonomicRank == "infraorder")] <- "Infraorder"
  data$TaxonomicRank[which(data$TaxonomicRank == "suborder")] <- "Suborder"
  data$TaxonomicRank[which(data$TaxonomicRank == "superorder")] <- "Superorder"
  data$TaxonomicRank[which(data$TaxonomicRank == "superfamily")] <- "Superfamily"
  data$TaxonomicRank[which(data$TaxonomicRank == "family")] <- "Family"
  data$TaxonomicRank[which(data$TaxonomicRank == "N/A")] <- NA
  data$TaxonomicRank[which(data$TaxonomicRank == "Superkingdom")] <- "Domain"
  data$TaxonomicRank[which(data$TaxonomicRank == "kingdom")] <- "Kingdom"
  return (data)
}


# adjust taxa names
adjust_names <- function (data) {
  # correct names
  data$WhichOrganism [grep("Xenart*", data$WhichOrganism)] <- "Xenarthra" #
  data$WhichOrganism [grep("xenarthra", data$WhichOrganism)] <- "Xenarthra" #
  data$WhichOrganism [which(data$WhichOrganism == "Acari")] <- "Acari"
  data$WhichOrganism [which(data$WhichOrganism == "Amphibians")] <- "Amphibia"
  data$WhichOrganism [which(data$WhichOrganism == "Ants")] <- "Formicidae"
  data$WhichOrganism [which(data$WhichOrganism == "ants")] <- "Formicidae"
  data$WhichOrganism [which(data$WhichOrganism == "ant")] <- "Formicidae"
  data$WhichOrganism [which(data$WhichOrganism == "ants (formicidae)")] <- "Formicidae"
  data$WhichOrganism [which(data$WhichOrganism == "aquatic turtles")] <- "Testudines"
  data$WhichOrganism [which(data$WhichOrganism == "aquatic turtles")] <- "Testudines"
  data$WhichOrganism [which(data$WhichOrganism == "arachnida")] <- "Arachnida"
  data$WhichOrganism [which(data$WhichOrganism == "Aracnida")] <- "Arachnida"
  data$WhichOrganism [which(data$WhichOrganism == "Aranae")] <- "Araneae"
  data$WhichOrganism [which(data$WhichOrganism == "Aranea")] <- "Araneae"
  data$WhichOrganism [which(data$WhichOrganism == "Arboreal ants (Formicidae)")] <- "Formicidae"
  data$WhichOrganism [which(data$WhichOrganism == "arthropods")] <- "Arthropoda"
  data$WhichOrganism [which(data$WhichOrganism == "Arthropods")] <- "Arthropoda"
  data$WhichOrganism [which(data$WhichOrganism == "Arthropods (Araneae)")] <- "Araneae"
  data$WhichOrganism [which(data$WhichOrganism == "Arthropods (Auchenorrhyncha)")] <- "Auchenorrhyncha"
  data$WhichOrganism [which(data$WhichOrganism == "Arthropods (Coleoptera)")] <- "Coleoptera"
  data$WhichOrganism [which(data$WhichOrganism == "Arthropods (Heteroptera)")] <- "Heteroptera"
  data$WhichOrganism [which(data$WhichOrganism == "bacteria")] <- "Bacteria"
  data$WhichOrganism [which(data$WhichOrganism == "bats")] <- "Chiroptera"
  data$WhichOrganism [which(data$WhichOrganism == "Bats")] <- "Chiroptera"
  data$WhichOrganism [which(data$WhichOrganism == "Beatles")] <- "Coleoptera"
  data$WhichOrganism [which(data$WhichOrganism == "bees")] <- "Apoidea"
  data$WhichOrganism [which(data$WhichOrganism == "bees (Apoidea)")] <- "Apoidea"
  data$WhichOrganism [which(data$WhichOrganism == "Beetles")] <- "Coleoptera"
  data$WhichOrganism [which(data$WhichOrganism == "beetles")] <- "Coleoptera"
  data$WhichOrganism [which(data$WhichOrganism == "Birds" )]<- "Aves"
  data$WhichOrganism [which(data$WhichOrganism == "breeding birds" )]<- "Aves"
  data$WhichOrganism [which(data$WhichOrganism == "birds" )]<- "Aves"
  data$WhichOrganism [which(data$WhichOrganism == "Bryophytes" )]<- "Bryophyta"
  data$WhichOrganism [which(data$WhichOrganism == "bryophytes" )]<- "Bryophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Butterflies" )]<- "Lepidoptera"
  data$WhichOrganism [which(data$WhichOrganism == "Carabidae" )]<- "Caraboidea"# "Carabidae" # ou "Caraboidea"
  data$WhichOrganism [which(data$WhichOrganism == "carabidae" )]<- "Caraboidea"# "Carabidae" # ou "Caraboidea"
  data$WhichOrganism [which(data$WhichOrganism == "carabids" )]<- "Caraboidea"# "Carabidae" # ou "Caraboidea"
  data$WhichOrganism [which(data$WhichOrganism == "Carabid beetles")] <- "Caraboidea"#"Carabidae"# ou "Caraboidea"
  data$WhichOrganism [which(data$WhichOrganism == "carnivora" )]<- "Carnivora" 
  data$WhichOrganism [which(data$WhichOrganism == "Chondricthyes" )]<- "Chondrichthyes"
  data$WhichOrganism [which(data$WhichOrganism == "Chrysophytes" )]<- "Chrysophyceae"
  data$WhichOrganism [which(data$WhichOrganism == "Clorophytes" )]<- "Chlorophyta"
  data$WhichOrganism [which(data$WhichOrganism == "coleptera" )]<- "Coleoptera" 
  data$WhichOrganism [which(data$WhichOrganism == "Coleptera" )]<- "Coleoptera" 
  data$WhichOrganism [which(data$WhichOrganism == "Copepoda calanoida" )]<- "Calanoida" 
  data$WhichOrganism [which(data$WhichOrganism == "corals" )]<- "Anthozoa" # 
  data$WhichOrganism [which(data$WhichOrganism == "crustacea" )]<- "Crustacea" # 
  data$WhichOrganism [which(data$WhichOrganism == "Cryptomonads" )]<- "Cryptophyceae" 
  data$WhichOrganism [which(data$WhichOrganism == "Cyanobacteria")] <- "Cyanobacteria"
  data$WhichOrganism [which(data$WhichOrganism == "Deadwood fungi" )]<- "Fungi" # 
  data$WhichOrganism [which(data$WhichOrganism == "Dinoflagelates" )]<- "Dinoflagellata"
  data$WhichOrganism [which(data$WhichOrganism == "DIrpodontia" )]<- "Diprotodontia" # 
  data$WhichOrganism [which(data$WhichOrganism == "Dung beetles (Scarabaeoidea)" )]<- "Scarabaeoidea" # 
  data$WhichOrganism [which(data$WhichOrganism == "Earthworms" )] <- "Lumbricina"
  data$WhichOrganism [which(data$WhichOrganism == "Echinoderms" )] <- "Echinodermata"
  data$WhichOrganism [which(data$WhichOrganism == "Ectomycorrhizal fungi")] <- "Fungi"
  data$WhichOrganism [which(data$WhichOrganism == "Epixylic lichens" )] <- "Bryophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Epigeal lichens" )] <- "Bryophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Ferns" )] <- "Polypodiopsida"
  data$WhichOrganism [which(data$WhichOrganism == "Fish" )] <- "Actinopterygii"
  data$WhichOrganism [which(data$WhichOrganism == "fish" )] <- "Actinopterygii"
  data$WhichOrganism [which(data$WhichOrganism == "Fishes" )] <- "Actinopterygii"
  data$WhichOrganism [which(data$WhichOrganism == "Frog" )] <- "Amphibia"
  data$WhichOrganism [which(data$WhichOrganism == "Frogs" )] <- "Amphibia"
  data$WhichOrganism [which(data$WhichOrganism == "Fruit-feeding butterflies (Nymphalidae)" )] <- "Nymphalidae"
  data$WhichOrganism [which(data$WhichOrganism == "fungi" )] <- "Fungi"
  data$WhichOrganism [which(data$WhichOrganism == "Saprobic fungi" )] <- "Fungi"
  data$WhichOrganism [which(data$WhichOrganism == "Gymnospermae" )] <- "Acrogymnospermae"
  data$WhichOrganism [which(data$WhichOrganism == "ground beetles (Carabidae)" )] <- "Carabidae"
  data$WhichOrganism [which(data$WhichOrganism == "hemiptera" )] <- "Hemiptera"
  data$WhichOrganism [which(data$WhichOrganism == "Herbaceous plants" )] <- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Herbs" )] <- "Tracheophyta" 
  data$WhichOrganism [which(data$WhichOrganism == "Hydriidae" )] <- "Hyriidae" 
  data$WhichOrganism [which(data$WhichOrganism == "Higher plants" )] <- "Tracheophyta" 
  data$WhichOrganism [which(data$WhichOrganism == "hoverflies (Syrphidae)" )] <- "Syrphidae" 
  data$WhichOrganism [which(data$WhichOrganism == "hymenoptera" )] <- "Hymenoptera"
  data$WhichOrganism [which(data$WhichOrganism == "insects" )] <- "Insecta" 
  data$WhichOrganism [which(data$WhichOrganism == "invertebrates (arthropoda)" )] <- "Arthropoda" 
  data$WhichOrganism [which(data$WhichOrganism == "Litter invertebrates" )] <- "Arthropoda" 
  data$WhichOrganism [which(data$WhichOrganism == "Large mammals" )] <- "Eutheria" 
  data$WhichOrganism [which(data$WhichOrganism == "longhorned beetles (Coleoptera: Cerambycidae)" )] <- "Cerambycidae" 
  data$WhichOrganism [which(data$WhichOrganism == "lichens" )] <- "Bryophyta" 
  data$WhichOrganism [which(data$WhichOrganism == "Lichens" )] <- "Bryophyta" 
  data$WhichOrganism [which(data$WhichOrganism == "Liquen" )] <- "Bryophyta" 
  data$WhichOrganism [which(data$WhichOrganism == "epiphytic lichens" )] <- "Bryophyta" 
  data$WhichOrganism [which(data$WhichOrganism == "Lizards" )] <- "Squamata" 
  data$WhichOrganism [which(data$WhichOrganism == "Macroinvertebrates (infauna) ANIMALIA")] <- "Metazoa"
  data$WhichOrganism [which(data$WhichOrganism == "macroalgae" )] <- "Eukaryota" 
  data$WhichOrganism [which(data$WhichOrganism == "malacostraca")] <- "Malacostraca" 
  data$WhichOrganism [which(data$WhichOrganism == "mammals")] <- "Eutheria"
  data$WhichOrganism [which(data$WhichOrganism == "Mammalia")] <- "Eutheria"
  data$WhichOrganism [which(data$WhichOrganism == "Mammal")] <- "Eutheria"
  data$WhichOrganism [which(data$WhichOrganism == "Mammals")] <- "Eutheria"
  data$WhichOrganism [which(data$WhichOrganism == "Mammals (<75kg)")] <- "Eutheria"
  data$WhichOrganism [which(data$WhichOrganism == "Metaphyta")] <- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Metaphyta")] <- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Mosses" )]<- "Bryophyta"
  data$WhichOrganism [which(data$WhichOrganism == "moths (Lepidoptera)" )]<- "Lepidoptera"
  data$WhichOrganism [which(data$WhichOrganism == "Oribatid mites" )]<- "Oribatida"
  data$WhichOrganism [which(data$WhichOrganism == "Plantae")] <- "Tracheophyta" # CF Metaphyta
  data$WhichOrganism [which(data$WhichOrganism == "Plants")] <- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Plant")] <- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "plants")] <- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Pollinators")] <- "Insecta"
  data$WhichOrganism [which(data$WhichOrganism == "protozoa (eukaryota)")] <- "Eukaryota"
  data$WhichOrganism [which(data$WhichOrganism == "Aquatic protists")] <- "Protista"
  data$WhichOrganism [which(data$WhichOrganism == "Pseudoscorpiones")] <- "Pseudoscorpiones"
  data$WhichOrganism [which(data$WhichOrganism == "Reptilia")] <- "Squamata"
  data$WhichOrganism [which(data$WhichOrganism == "Reptiles ")] <- "Squamata"
  data$WhichOrganism [which(data$WhichOrganism == "reptiles ")] <- "Squamata"
  data$WhichOrganism [which(data$WhichOrganism == "Richardsonianidae")] <- "Hirudinoidea" # Not found, the previous rank
  data$WhichOrganism [which(data$WhichOrganism == "Rhopalocera")] <- "Rhopaloceras"
  data$WhichOrganism [which(data$WhichOrganism == "Salamanders")] <- "Caudata"
  data$WhichOrganism [which(data$WhichOrganism == "Saproxylic beetles")] <- "Coleoptera"
  data$WhichOrganism [which(data$WhichOrganism == "seagrass (Alismatales)")] <- "Alismatales"
  data$WhichOrganism [which(data$WhichOrganism == "shellfish (animalia)")] <- "Animalia"
  data$WhichOrganism [which(data$WhichOrganism == "small mammals")] <- "Eutheria"
  data$WhichOrganism [which(data$WhichOrganism == "Small mammals")] <- "Eutheria"
  data$WhichOrganism [which(data$WhichOrganism == "spiders")] <- "Araneae"
  data$WhichOrganism [which(data$WhichOrganism == "Spiders")] <- "Araneae"
  data$WhichOrganism [which(data$WhichOrganism == "Soil bacteria")] <- "Bacteria"
  data$WhichOrganism [which(data$WhichOrganism == "termites")] <- "Dictyoptera"
  data$WhichOrganism [which(data$WhichOrganism == "Termites" )]<- "Dictyoptera"
  data$WhichOrganism [which(data$WhichOrganism == "Tree" )]<- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "trees" )]<- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Trees" )]<- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Vegetation (plantae)" )]<- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "true bugs" )]<- "Hemiptera"
  data$WhichOrganism [which(data$WhichOrganism == "vascular plants")] <- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Vascular plants")] <- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Vegetation")] <- "Tracheophyta" # CF rank in GUI LONGO
  data$WhichOrganism [which(data$WhichOrganism == "Wood-inhabiting fingi")] <- "Fungi"
  data$WhichOrganism [which(data$WhichOrganism == "Woody plants")] <- "Tracheophyta"
  data$WhichOrganism [which(data$WhichOrganism == "Zyganeidae")] <- "Zygaenidae"

  return (data)
  
}

